### ISSUE TITLE
cli: Allow -j first

### ISSUE THREAD

**Issue by srl295** [IBM-Cloud/gp-java-tools#102]
minor: would be nice to be able to have `-j` to be before the action:

> `java -jar …   -j gpconfig.json  list`

> `java -jar …   -j gpconfig.json  show -b MyBundle `

(then `java -jar …   -j gpconfig.json …` could be a shell script )

**Comment by yumaoka** [comment]
This cannot be achieved with JCommander used by GP CLI.

**Comment by yumaoka** [comment]
No plan to fix this issue. Closing.
